#!/bin/bash

# 🚀 SKAVIYO ADMIN PANEL - STARTUP GUIDE

echo "╔════════════════════════════════════════════════════════════════════════╗"
echo "║                                                                        ║"
echo "║              🚀 SKAVIYO ADMIN PANEL - QUICK START 🚀                   ║"
echo "║                                                                        ║"
echo "╚════════════════════════════════════════════════════════════════════════╝"
echo ""

echo "📊 COMPONENTS TO START"
echo "════════════════════════════════════════════════════════════════════════"
echo "1. Backend API Server (Express + MySQL)"
echo "   └─ Port: 4000"
echo "   └─ URL: http://localhost:4000"
echo ""
echo "2. Frontend Admin Dashboard (React + Vite)"
echo "   └─ Port: 5173"
echo "   └─ URL: http://localhost:5173"
echo ""

echo "⚙️ PREREQUISITES"
echo "════════════════════════════════════════════════════════════════════════"
echo "✓ Node.js 18+ installed"
echo "✓ MySQL database running"
echo "✓ Backend DATABASE_URL configured in .env"
echo ""

echo "🔧 STEP 1: INSTALL DEPENDENCIES"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "Backend:"
echo "  $ cd backend"
echo "  $ npm install"
echo ""
echo "Frontend:"
echo "  $ cd frontend"
echo "  $ npm install"
echo ""

echo "✨ STEP 2: START BACKEND SERVER"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "Option A - Development Mode (with hot reload):"
echo "  $ cd backend"
echo "  $ npm run dev"
echo ""
echo "Option B - Production Mode:"
echo "  $ cd backend"
echo "  $ npm start"
echo ""
echo "Expected Output:"
echo "  [SERVER] Skaviyo Backend running on http://localhost:4000"
echo "  [SERVER] Health check: http://localhost:4000/health"
echo ""

echo "✨ STEP 3: START FRONTEND DASHBOARD (in new terminal)"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "Development Mode (with hot reload):"
echo "  $ cd frontend"
echo "  $ npm run dev"
echo ""
echo "Expected Output:"
echo "  ✓ ready in XXms"
echo "  ➜  Local:   http://localhost:5173/"
echo ""

echo "✅ VERIFICATION"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "Backend Health Check:"
echo "  curl http://localhost:4000/health"
echo ""
echo "Expected Response:"
echo "  {\"success\":true,\"message\":\"Server is running\"}"
echo ""

echo "🔗 API ENDPOINTS TO TEST"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "Authentication:"
echo "  POST   /api/v1/auth/register"
echo "  POST   /api/v1/auth/login"
echo "  GET    /api/v1/auth/me"
echo ""
echo "Admin:"
echo "  GET    /api/v1/admin/details"
echo "  GET    /api/v1/admin/all"
echo "  GET    /api/v1/admin/customers"
echo "  GET    /api/v1/admin/customers/:id"
echo "  GET    /api/v1/admin/vendors"
echo "  GET    /api/v1/admin/vendors/:id"
echo ""

echo "📱 FRONTEND PAGES"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "Homepage Dashboard:"
echo "  http://localhost:5173"
echo ""
echo "Features:"
echo "  ✓ Header with navigation"
echo "  ✓ Search bar"
echo "  ✓ Announcement banner"
echo "  ✓ Hero section"
echo "  ✓ Category grid (8 categories)"
echo ""

echo "📝 ENVIRONMENT SETUP"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "Backend .env (backend/.env):"
echo "  PORT=4000"
echo "  DATABASE_URL=mysql://user:password@localhost:3306/skaviyo"
echo "  JWT_SECRET=your_secret_key"
echo "  CORS_ORIGIN=http://localhost:3001"
echo ""

echo "🐛 TROUBLESHOOTING"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "Backend won't start?"
echo "  1. Check if port 4000 is available: lsof -i :4000"
echo "  2. Verify MySQL is running"
echo "  3. Check DATABASE_URL in .env is correct"
echo "  4. Run: npm install"
echo ""
echo "Frontend won't start?"
echo "  1. Check if port 5173 is available: lsof -i :5173"
echo "  2. Run: npm install"
echo "  3. Check Node version: node -v (should be 18+)"
echo ""
echo "API connection issues?"
echo "  1. Verify backend is running on port 4000"
echo "  2. Check CORS_ORIGIN in backend .env"
echo "  3. Check browser console for errors"
echo ""

echo "🎯 NEXT STEPS"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "1. Start Backend:"
echo "   cd backend && npm run dev"
echo ""
echo "2. Start Frontend (in new terminal):"
echo "   cd frontend && npm run dev"
echo ""
echo "3. Open in Browser:"
echo "   http://localhost:5173"
echo ""
echo "4. Test API:"
echo "   curl http://localhost:4000/health"
echo ""

echo "📚 DOCUMENTATION"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "Backend:"
echo "  ✓ POSTGRESQL_TO_MYSQL_MIGRATION.md"
echo "  ✓ MYSQL_QUERY_REFERENCE.md"
echo ""
echo "Frontend:"
echo "  ✓ IMPLEMENTATION_GUIDE.md"
echo "  ✓ STYLING_GUIDE.md"
echo "  ✓ QUICK_REFERENCE.md"
echo "  ✓ START_HERE.md"
echo ""

echo "╔════════════════════════════════════════════════════════════════════════╗"
echo "║                                                                        ║"
echo "║                    🚀 YOU'RE READY TO GO! 🚀                           ║"
echo "║                                                                        ║"
echo "║  Backend: http://localhost:4000                                        ║"
echo "║  Frontend: http://localhost:5173                                       ║"
echo "║                                                                        ║"
echo "╚════════════════════════════════════════════════════════════════════════╝"
echo ""
